export const cardList = [
  {
    id: 1,
    theme: "Web Design",
    title: "Названия задачи",
    date: "30.10.23",
    status: "БЕЗ СТАТУСА",
  },
  {
    id: 2,
    theme: "Research",
    title: "Названия задачи",
    date: "30.10.23",
    status: "БЕЗ СТАТУСА",
  },
  {
    id: 3,
    theme: "Web Design",
    title: "Названия задачи",
    date: "30.10.23",
    status: "БЕЗ СТАТУСА",
  },
  {
    id: 4,
    theme: "Copywriting",
    title: "Названия задачи",
    date: "30.10.23",
    status: "БЕЗ СТАТУСА",
  },
  {
    id: 5,
    theme: "Research",
    title: "Названия задачи",
    date: "30.10.23",
    status: "БЕЗ СТАТУСА",
  },
  {
    id: 6,
    theme: "Research",
    title: "Названия задачи",
    date: "30.10.23",
    status: "НУЖНО СДЕЛАТЬ",
  },
  {
    id: 7,
    theme: "Research",
    title: "Названия задачи",
    date: "30.10.23",
    status: "В РАБОТЕ",
  },
  {
    id: 8,
    theme: "Copywriting",
    title: "Названия задачи",
    date: "30.10.23",
    status: "В РАБОТЕ",
  },
  {
    id: 9,
    theme: "Web Design",
    title: "Названия задачи",
    date: "30.10.23",
    status: "В РАБОТЕ",
  },
  {
    id: 10,
    theme: "Research",
    title: "Названия задачи",
    date: "30.10.23",
    status: "ТЕСТИРОВАНИЕ",
  },
  {
    id: 11,
    theme: "Research",
    title: "Названия задачи",
    date: "30.10.23",
    status: "ГОТОВО",
  },
];
